config/routes.rb
Rails.application.routes.draw do
  resources :applications

  devise_for :users

  resources :internships do
    resources :applications, only: [:new, :create]
  end

  resources :companies do
    resources :internships
  end

  root to: "internships#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :internship
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :update, :destroy]
  before_action :set_internship, only: [:new, :create]
  before_action :authenticate_user!

  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @application = @internship.applications.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = @internship.applications.new(application_params)
    @application.user_id =current_user.id

    respond_to do |format|
      if @application.save
        format.html { redirect_to @internship, notice: 'Application was successfully created.' }
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: 'Application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

  def set_internship
    @internship = Internship.find(params[:internship_id])
  end
    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:answer, :status)
    end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.erb
<%= form_for([@internship, @application]) do |form| %>
  <% if application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <strong>Why do you want to apply for this Internship?</strong>
  <div class="field">
    <%= form.label :answer %>
    <%= form.text_area :answer, class: "form-control" %>
  </div>

  <div class="actions">'
    <%= form.submit class: "btn btn-primary btn-sm"  %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing Application</h1>

<%= render 'form', application: @application %>

<%= link_to 'Show', @application, class: "btn btn-outline-secondary btn-sm" %>
<%= link_to 'Back', applications_path, class: "btn btn-outline-secondary btn-sm" %>

app/views/applications/index.html.erb
<h1>My Applications</h1>

    <% current_user.applications.each do |application| %>
    <div class="card">
      <div class="card-header">
        <%=time_ago_in_words(application.created_at)%> ago
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= Internship.find(application.internship_id).title%></h5>
        <p class="card-text"><%= application.answer %></p>
        <p class="card-text"><%= application.status %></p>
        <div class="btn-group" role="group" aria-label="Basic example">
          <%= link_to 'Show', application, class: "btn btn-outline-dark btn-sm" %>
          <%= link_to 'Edit', edit_application_path(application), class: "btn btn-outline-dark btn-sm" %>
          <%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-dark btn-sm" %>
        </div>
      </div>
    </div>
  <br>
    <% end %>

app/views/applications/new.html.erb
<h1>New Application</h1>
<%= render 'form', application: @application %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Answer:</strong>
  <%= @application.answer %>
</p>

<p>
  <strong>Status:</strong>
  <%= @application.status %>
</p>

<p>
  <strong>Why do you want to apply for this internship?</strong>
  <%= @application.answer %>
</p>

<%= link_to 'Edit', edit_application_path(@application), class: "btn btn-outline-secondary btn-sm" %> |
<%= link_to 'Back', applications_path, class: "btn btn-outline-secondary btn-sm" %>