config/routes.rb
Rails.application.routes.draw do
  resources :applications

  devise_for :users

  resources :internships do
    resources :applications, only: [:new, :create]
  end

  resources :companies do
    resources :internships
  end

  root to: "internships#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :internships, dependent: :destroy
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = current_user.companies.build
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = current_user.companies.build(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :description)
    end
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, :class=>"form-control" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary btn-sm" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', @company, class: "btn btn-outline-secondary btn-sm" %>

app/views/companies/index.html.erb
<h1>Companies</h1>

<table id="company_table" class="display">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>No. of Internships</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.description %></td>
        <td><%= company.internships.count %></td>
        <td><%= link_to 'Show', company, class: "btn btn-outline-secondary btn-sm" %>
          <% if can? :destroy, Company %>
          <%= link_to 'Edit', edit_company_path(company), class: "btn btn-outline-secondary btn-sm" %>
           <%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-secondary btn-sm" %>
           <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
    $(document).ready( function () {
        $('#company_table').DataTable();
    } );
</script>

<br>
<% if can? :new, Company %>
<%= link_to 'New Company', new_company_path, class: "btn btn-outline-secondary btn-sm"  %>
<%end %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path, class: "btn btn-outline-secondary btn-sm" %>

app/views/companies/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= simple_format @company.description %>
</p>


<% if can? :edit, Company %>
  <%= link_to 'Edit Company Details', edit_company_path(@company), class: "btn btn-outline-secondary btn-sm" %>
<%end %>
<% if can? :create, Internship %>
  <%= link_to 'Post an Internship', new_company_internship_path(@company), class: "btn btn-outline-secondary btn-sm"  %>
<%end %>

<br>


<h4>Internships offered by <%= @company.name %></h4>
<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Apply By</th>
    <th>Start</th>

    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% @company.internships.each do |internship| %>
    <tr>
      <td><%= internship.title %></td>
      <td><%= internship.deadline %></td>
      <td><%= internship.start %></td>
      <td><%= link_to 'Show', company_internship_path(@company,internship), class: "btn btn-outline-secondary btn-sm" %></td>
      <% if can? :destroy, Internship %>
        <td><%= link_to 'Destroy', [@company, internship], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-secondary btn-sm" %></td>
      <% end %>
        </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Back', companies_path, class: "btn btn-outline-secondary btn-sm" %>