config/routes.rb
Rails.application.routes.draw do
  resources :applications

  devise_for :users

  resources :internships do
    resources :applications, only: [:new, :create]
  end

  resources :companies do
    resources :internships
  end

  root to: "internships#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/internship.rb
class Internship < ApplicationRecord
  belongs_to :company
  has_many :applications, dependent: :destroy
end

app/controllers/internships_controller.rb
class InternshipsController < ApplicationController
  before_action :set_company, only: [:new, :create]
  before_action :set_internship, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /internships
  # GET /internships.json
  def index
    @internships = Internship.all
  end

  # GET /internships/1
  # GET /internships/1.json
  def show
  end

  # GET /internships/new
  def new
    @internship = @company.internships.new
  end

  # GET /internships/1/edit
  def edit
  end

  # POST /internships
  # POST /internships.json
  def create
    @internship = @company.internships.new(internship_params)

    respond_to do |format|
      if @internship.save
        format.html { redirect_to @company, notice: 'Internship was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /internships/1
  # PATCH/PUT /internships/1.json
  def update
    respond_to do |format|
      if @internship.update(internship_params)
        format.html { redirect_to internships_path, notice: 'Internship was successfully updated.' }
        format.json { render :show, status: :ok, location: @internship }
      else
        format.html { render :edit }
        format.json { render json: @internship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /internships/1
  # DELETE /internships/1.json
  def destroy
    @internship.destroy
    respond_to do |format|
      format.html { redirect_to internships_path, notice: 'Internship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_internship
      @internship = Internship.find(params[:id])
    end

    def set_company
      @company = Company.find(params[:company_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def internship_params
      params.require(:internship).permit(:id, :title, :description, :eligibility, :deadline, :location, :duration, :stipend, :start)
    end
end

app/helpers/internships_helper.rb
module InternshipsHelper
end

app/views/internships/_form.html.erb
<%= form_for([@company, @internship]) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :eligibility %>
    <%= form.text_area :eligibility, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :deadline %>
    <%= form.date_select :deadline , class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.text_field :duration, class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :stipend %>
    <%= form.number_field :stipend, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.date_select :start, class: "form-control" %>
  </div>


  <div class="actions">
    <%= form.submit class: "btn btn-primary btn-sm"  %>
  </div>
<% end %>

app/views/internships/edit.html.erb
<h1>Editing Internship</h1>

<%= render 'form', internship: @internship %>
<%= link_to 'Back', internship_path, class: "btn btn-outline-secondary btn-sm" %>

app/views/internships/index.html.erb
<h1>Internships</h1>

<table id="table_id" class="display">
  <thead>
    <tr>
      <th>Title</th>
      <th>Company</th>
      <th>Apply By</th>
      <th>Start</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @internships.each do |internship| %>
      <tr>
        <td><%= internship.title %></td>
        <td><%= link_to Company.find(internship.company_id).name, Company.find(internship.company_id),class: "btn btn-outline-dark" %></td>
        <td><%= internship.deadline %></td>
        <td><%= internship.start %></td>
        <td>
          <%= link_to 'Show', internship_path(internship), class: "btn btn-outline-secondary btn-sm" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<script>
    $(document).ready( function () {
        $('#table_id').DataTable();
    } );
</script>

app/views/internships/new.html.erb
<h1>New Internship</h1>

<%= render 'form', internship: @internship %>
<%= link_to 'Back', companies_path, class: "btn btn-outline-secondary btn-sm" %>

app/views/internships/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @internship.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= simple_format @internship.description %>
</p>

<p>
  <strong>Eligibility:</strong>
  <%= simple_format @internship.eligibility %>
</p>

<p>
  <strong>Apply By:</strong>
  <%= @internship.deadline %>
</p>

<p>
  <strong>Location:</strong>
  <%= @internship.location %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @internship.duration %>
</p>

<p>
  <strong>Stipend (INR per month):</strong>
  <%= @internship.stipend %>
</p>

<p>
  <strong>Start:</strong>
  <%= @internship.start %>
</p>
<% if can? :create, Application %>
  <%= link_to 'Apply for Internship', new_internship_application_path(@internship), class: "btn btn-outline-secondary btn-sm" %>
<% end %>
<br>
<% if can? :manage, Internship %>
  <%= link_to 'Edit', edit_internship_path(@internship), class: "btn btn-outline-secondary btn-sm" %> |
  <%= link_to 'Destroy', @internship, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-secondary btn-sm" %>
<% end %>